### ISSUE TITLE
Plato migration failure

### ISSUE THREAD

**Issue by tsutsu** [node-real/bsc-erigon#78] opened 2023-05-16 23:20 UTC
Erigon version: v1.0.5

OS & Version: Linux/amd64 (Ubuntu 22.04)

Node reaches upgrade block, upgrade fails; node is restarted; consensus-engine in upgraded regime seems to fail to process existing snapshot state data, then fails again:

````
[INFO] [05-16|22:28:40.143] [2/15 Headers] Waiting for headers...    from=29861022
[INFO] [05-16|22:28:43.076] [2/15 Headers] Processed                 highest inserted=29861023 age=0
[INFO] [05-16|22:28:43.094] [7/15 Execution] Completed on            block=29861023
[INFO] [05-16|22:28:43.102] Commit cycle                             in=2.170581ms
[INFO] [05-16|22:28:43.102] Timings (slower than 50ms)               Headers=2.933s
[INFO] [05-16|22:28:43.102] Tables                                   PlainState=32.8GB AccountChangeSet=16.4GB StorageChangeSet=69.0GB BlockTransaction=132.1GB TransactionLog=87.7GB Fr>
[INFO] [05-16|22:28:43.102] RPC Daemon notified of new headers       from=29861022 to=29861023 hash=0x566c57e3b41a07e504bc3305516eb50797814a766e6b9ddb0c1ecffc2b50e12a header sending=10>
[INFO] [05-16|22:28:43.103] [2/15 Headers] Waiting for headers...    from=29861023
[EROR] [05-16|22:28:46.112] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861024 blockHash=0x5d78b2201c37e72a5d3d33a4182aaa6cb0bf4132ad5aa01afe179759a>
[INFO] [05-16|22:28:46.113] [2/15 Headers] Processed                 highest inserted=29861024 age=0
[INFO] [05-16|22:28:46.114] [7/15 Execution] Completed on            block=29861024
[EROR] [05-16|22:28:46.114] [9/15 IntermediateHashes] Wrong trie root of block 29861024: 74c3fec75ed11d77d2d3f5c9285f1262cf262217204899218bdcc8632d50c2a2, expected (from header): 7d0c4>
[WARN] [05-16|22:28:46.114] Unwinding due to incorrect root hash     to=29861023
[INFO] [05-16|22:28:46.114] UnwindTo                                 block=29861023 bad_block_hash=0x5d78b2201c37e72a5d3d33a4182aaa6cb0bf4132ad5aa01afe179759a8a4d3ff
[INFO] [05-16|22:28:46.114] [8/15 HashState] Unwinding started       from=29861024 to=29861023 storage=false codes=true
[INFO] [05-16|22:28:46.114] [8/15 HashState] Unwinding started       from=29861024 to=29861023 storage=false codes=false
[INFO] [05-16|22:28:46.114] [8/15 HashState] Unwinding started       from=29861024 to=29861023 storage=true codes=false
[INFO] [05-16|22:28:46.115] [7/15 Execution] Unwind Execution        from=29861024 to=29861023
[INFO] [05-16|22:28:46.115] [2/15 Headers] Waiting for headers...    from=29861023
[WARN] [05-16|22:28:46.129] [downloader] Rejected header marked as bad hash=0x5d78b2201c37e72a5d3d33a4182aaa6cb0bf4132ad5aa01afe179759a8a4d3ff height=29861024
[WARN] [05-16|22:28:46.171] [downloader] Rejected header marked as bad hash=0x5d78b2201c37e72a5d3d33a4182aaa6cb0bf4132ad5aa01afe179759a8a4d3ff height=29861024
[WARN] [05-16|22:28:46.174] [downloader] Rejected header marked as bad hash=0x5d78b2201c37e72a5d3d33a4182aaa6cb0bf4132ad5aa01afe179759a8a4d3ff height=29861024

...

Stopping Erigon blockchain node...
[INFO] [05-16|22:31:47.323] Got interrupt, shutting down...
[INFO] [05-16|22:31:47.323] Exiting Engine...
[INFO] [05-16|22:31:47.323] Exiting...
[INFO] [05-16|22:31:47.323] RPC server shutting down
[WARN] [05-16|22:31:47.323] Failed to serve http endpoint            err="http: Server closed"
[INFO] [05-16|22:31:47.323] HTTP endpoint closed                     url=127.0.0.1:9545
[INFO] [05-16|22:31:47.323] RPC server shutting down
[INFO] [05-16|22:31:47.323] RPC server shutting down
[WARN] [05-16|22:31:47.323] Failed to serve http endpoint            err="http: Server closed"
[INFO] [05-16|22:31:47.323] Engine HTTP endpoint close               url=127.0.0.1:9551
blockchain-node@chapel.service: Deactivated successfully.
Stopped Erigon blockchain node.
blockchain-node@chapel.service: Consumed 30min 23.843s CPU time.
Started Erigon blockchain node.
[INFO] [05-16|22:31:57.980] logging to file system                   log dir=/scratch/node/chapel/logs file prefix=erigon log level=crit json=false
[INFO] [05-16|22:31:57.985] Build info                               git_branch= git_tag= git_commit=
[INFO] [05-16|22:31:57.985] Starting Erigon on Chapel testnet...
[INFO] [05-16|22:31:57.986] Maximum peer count                       ETH=200 total=200
[INFO] [05-16|22:31:57.986] starting HTTP APIs                       APIs=admin,debug,eth,net,web3,erigon
[INFO] [05-16|22:31:57.986] torrent verbosity                        level=WRN
[INFO] [05-16|22:31:57.986] [torrent] Public IP                      ip=15.235.54.154
[INFO] [05-16|22:31:57.987] Set global gas cap                       cap=50000000
[INFO] [05-16|22:31:57.991] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=64mb upload.rate=4mb
[INFO] [05-16|22:31:57.991] Opening Database                         label=chaindata path=/scratch/node/chapel/chaindata
[INFO] [05-16|22:31:57.991] [db] params: growStep=2GB, mapsSize=7TB, shrinkThreshold=-1, pageSize=16KB, label=chaindata, WriteMap=false, Durable=false, NoReadahead=true,
[INFO] [05-16|22:31:57.992] Initialised chain configuration          config="{ChainID: 97 Ramanujan: 1010000, Niels: 1014369, MirrorSync: 5582500, Bruno: 13837000, Euler: 19203503, Gib>
[WARN] [05-16|22:31:57.992] Incorrect snapshot enablement            got=true change_to=false
[INFO] [05-16|22:31:57.992] Effective                                prune_flags="--prune.c.older=90000" snapshot_flags= history.v3=false
[INFO] [05-16|22:31:57.994] Initialising Ethereum protocol           network=97
[INFO] [05-16|22:31:58.408] Starting private RPC server              on=127.0.0.1:10097
[INFO] [05-16|22:31:58.408] new subscription to logs established
[INFO] [05-16|22:31:58.408] rpc filters: subscribing to Erigon events
[INFO] [05-16|22:31:58.409] new subscription to newHeaders established
[INFO] [05-16|22:31:58.409] New txs subscriber joined
[INFO] [05-16|22:31:58.409] Reading JWT secret                       path=/scratch/node/chapel/jwt.hex
[INFO] [05-16|22:31:58.410] HTTP endpoint opened for Engine API      url=127.0.0.1:9551 ws=true ws.compression=true
[INFO] [05-16|22:31:58.410] HTTP endpoint opened                     url=127.0.0.1:9545 ws=true ws.compression=true grpc=false
[INFO] [05-16|22:31:58.414] Started P2P networking                   version=67 self=enode://412e32aca65b49a8f35c29214fbb5b0b4a7a44554d0e10fc7c71ffd32caa00ca6e46cb2f0d0f23a6b3f1f8abf7c>
[INFO] [05-16|22:31:58.414] Started P2P networking                   version=66 self=enode://412e32aca65b49a8f35c29214fbb5b0b4a7a44554d0e10fc7c71ffd32caa00ca6e46cb2f0d0f23a6b3f1f8abf7c>
[INFO] [05-16|22:31:58.417] Started P2P networking                   version=68 self=enode://412e32aca65b49a8f35c29214fbb5b0b4a7a44554d0e10fc7c71ffd32caa00ca6e46cb2f0d0f23a6b3f1f8abf7c>
[INFO] [05-16|22:31:58.419] [txpool] Started
[INFO] [05-16|22:31:58.419] [2/15 Headers] Waiting for headers...    from=29861023
[INFO] [05-16|22:32:01.333] New txs subscriber joined
[INFO] [05-16|22:32:01.333] new subscription to newHeaders established
[INFO] [05-16|22:32:58.409] [txpool] stat                            pending=13 baseFee=0 queued=12 alloc=91.9MB sys=208.4MB
[INFO] [05-16|22:33:57.994] [p2p] GoodPeers                          eth67=2 eth66=7
[INFO] [05-16|22:33:58.409] [txpool] stat                            pending=45 baseFee=0 queued=34 alloc=83.7MB sys=212.9MB
[INFO] [05-16|22:34:12.726] [2/15 Headers] Inserting headers         progress=29861023 queue=1
[EROR] [05-16|22:34:12.728] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861025 blockHash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb5810>
[EROR] [05-16|22:34:12.731] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861026 blockHash=0x82506ae10091cdaf01811487b8c2a3ae5be81f7c99120009baa1e0b53>
[EROR] [05-16|22:34:12.731] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861026 blockHash=0x82506ae10091cdaf01811487b8c2a3ae5be81f7c99120009baa1e0b53>
[EROR] [05-16|22:34:12.733] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861027 blockHash=0x7f5f5a7760aff9ec6dae628f0893c17454ef64fb89b5b058822ad2a86>
[EROR] [05-16|22:34:12.733] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861027 blockHash=0x7f5f5a7760aff9ec6dae628f0893c17454ef64fb89b5b058822ad2a86>
[EROR] [05-16|22:34:12.735] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861028 blockHash=0xfba701379efc76254003876ae4aad7e37c707aa06e23cae64753d5514>
[EROR] [05-16|22:34:12.735] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861028 blockHash=0xfba701379efc76254003876ae4aad7e37c707aa06e23cae64753d5514>
[EROR] [05-16|22:34:12.737] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861029 blockHash=0xc04294d88837a0a21a6e829ae28bc512707fcc8cd3210dfcb9f5a4d7e>

...

[EROR] [05-16|22:34:12.863] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861092 blockHash=0x8c6b3e699d16ee084a53ce1a8e0923e6802d49a9709632db275fa7f18>
[EROR] [05-16|22:34:12.863] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861092 blockHash=0x8c6b3e699d16ee084a53ce1a8e0923e6802d49a9709632db275fa7f18>
[EROR] [05-16|22:34:12.866] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861093 blockHash=0x148ecf0c8955137cf4d45ca49b8779123201052cfd808b08d1b3df158>
[EROR] [05-16|22:34:12.866] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29861093 blockHash=0x148ecf0c8955137cf4d45ca49b8779123201052cfd808b08d1b3df158>
[INFO] [05-16|22:34:12.867] [2/15 Headers] Processed                 highest inserted=29861093 age=1m59s
[INFO] [05-16|22:34:12.867] [2/15 Headers] DONE                      in=2m14.448336512s
[INFO] [05-16|22:34:12.889] [5/15 Bodies] Processing bodies...       from=29861023 to=29861093
[INFO] [05-16|22:34:12.937] [5/15 Bodies] Processed                  highest=29861093
[INFO] [05-16|22:34:12.937] [6/15 Senders] Started                   from=29861023 to=29861093
[INFO] [05-16|22:34:12.940] [7/15 Execution] Blocks execution        from=29861023 to=29861093
[WARN] [05-16|22:34:12.941] [7/15 Execution] Execution failed        block=29861025 hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628 err="mismatched receipt head>
[INFO] [05-16|22:34:12.941] UnwindTo                                 block=29861024 bad_block_hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628
[INFO] [05-16|22:34:12.941] [7/15 Execution] Completed on            block=29861024
[INFO] [05-16|22:34:12.942] Timings (slower than 50ms)               Headers=2m14.448s
[INFO] [05-16|22:34:12.942] RPC Daemon notified of new headers       from=29861023 to=29861093 hash=0x0000000000000000000000000000000000000000000000000000000000000000 header sending=42>
[INFO] [05-16|22:34:12.942] [2/15 Headers] Waiting for headers...    from=29861024
[WARN] [05-16|22:34:12.959] [downloader] Rejected header marked as bad hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628 height=29861025
[WARN] [05-16|22:34:12.971] [downloader] Rejected header marked as bad hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628 height=29861025
[WARN] [05-16|22:34:12.973] [downloader] Rejected header marked as bad hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628 height=29861025
[WARN] [05-16|22:34:12.975] [downloader] Rejected header marked as bad hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628 height=29861025
[WARN] [05-16|22:34:12.984] [downloader] Rejected header marked as bad hash=0xcff232a0021469422520093a26ad86a95e8c58fc533c9d97dbceb581026f2628 height=29861025

````

**Comment by sjlee1125** [comment] 2023-05-17 00:42
I have the same failure

**Comment by setunapo** [comment] 2023-05-17 02:22
wait, we are working on it, will schedule a new release

**Comment by touhonoob** [comment] 2023-05-17 02:34
The latest release doesn't work for me
```
[7/15 Execution] Executed blocks         number=29861023 blk/s=0.0 tx/s=0.0 Mgas/s=0.0 gasState=0.00 batch=483B alloc=105.1MB sys=225.4MB
May 17 02:29:58  erigon[61898]: [INFO] [05-17|02:29:58.301] Apply upgrade plato at height 29861024   system-contract-upgrade=chapel
May 17 02:29:58  erigon[61898]: [INFO] [05-17|02:29:58.301] Upgrade contract 0x0000000000000000000000000000000000001000 to commit https://github.com/bnb-chain/bsc-genesis-contract/commit/0f352c4623898d92664a46cbfc26c52b79aad838 system-contract-upgrade=chapel
May 17 02:29:58  erigon[61898]: [INFO] [05-17|02:29:58.301] Upgrade contract 0x0000000000000000000000000000000000001001 to commit https://github.com/bnb-chain/bsc-genesis-contract/commit/0f352c4623898d92664a46cbfc26c52b79aad838 system-contract-upgrade=chapel
May 17 02:30:18  erigon[61898]: [INFO] [05-17|02:30:18.786] [p2p] GoodPeers                          eth66=4 eth67=2
May 17 02:32:18  erigon[61898]: [INFO] [05-17|02:32:18.786] [p2p] GoodPeers                          eth66=5 eth67=3
May 17 02:33:17  erigon[61898]: [WARN] [05-17|02:33:17.845] [7/15 Execution] Execution failed        block=29861200 hash=0xf21360c3b70fbaf1ebaa67fb58b3a7a5f3301d54c076554fb0f1619285943a6d err="the length of systemTxs is still 1"
May 17 02:33:17  erigon[61898]: [INFO] [05-17|02:33:17.845] UnwindTo                                 block=29861199 bad_block_hash=0xf21360c3b70fbaf1ebaa67fb58b3a7a5f3301d54c076554fb0f1619285943a6d
May 17 02:33:18  erigon[61898]: [INFO] [05-17|02:33:18.002] [7/15 Execution] Completed on            block=29861199
May 17 02:33:18  erigon[61898]: [INFO] [05-17|02:33:18.002] [7/15 Execution] DONE                    in=5m0.272139545s
May 17 02:33:18  erigon[61898]: [INFO] [05-17|02:33:18.174] Timings (slower than 50ms)               Headers=1m50.469s BlockHashes=2.299s Bodies=5.61s Senders=84ms Execution=5m0.272s Unwind Bodies=133ms
May 17 02:33:18  erigon[61898]: [INFO] [05-17|02:33:18.178] RPC Daemon notified of new headers       from=29861022 to=29865811 hash=0x0000000000000000000000000000000000000000000000000000000000000000 header sending=3.592423ms log sending=291ns
May 17 02:33:18  erigon[61898]: [INFO] [05-17|02:33:18.179] [2/15 Headers] Waiting for headers...    from=29861199
May 17 02:33:18  erigon[61898]: [WARN] [05-17|02:33:18.674] [downloader] Rejected header marked as bad hash=0xf21360c3b70fbaf1ebaa67fb58b3a7a5f3301d54c076554fb0f1619285943a6d height=29861200
```

**Comment by tsutsu** [comment] 2023-05-17 03:19
@touhonoob Same here; and also, unwinding `state_stages` back past the upgrade height now seems to be impossible:

```
ubuntu@bsc-mainnet:~/erigon$ sudo -u blockchain -- ./build/bin/integration state_stages --unwind=253 --datadir=/scratch/node/chapel --chain=chapel
INFO[05-17|03:17:41.824] logging to file system                   log dir=/scratch/node/chapel/logs file prefix=erigon log level=info json=false
INFO[05-17|03:17:42.255] UnwindTo                                 block=29860774 bad_block_hash=0x0000000000000000000000000000000000000000000000000000000000000000
INFO[05-17|03:17:42.301] [8/15 HashState] Unwinding started       from=29861027 to=29860774 storage=false codes=true
INFO[05-17|03:17:42.304] [8/15 HashState] Unwinding started       from=29861027 to=29860774 storage=false codes=false
INFO[05-17|03:17:42.311] [8/15 HashState] Unwinding started       from=29861027 to=29860774 storage=true codes=false
INFO[05-17|03:17:42.329] [9/15 IntermediateHashes] Unwinding      from=29861027 to=29860774 csbucket=AccountChangeSet
INFO[05-17|03:17:42.335] [9/15 IntermediateHashes] Unwinding      from=29861027 to=29860774 csbucket=StorageChangeSet
EROR[05-17|03:17:42.403] [9/15 IntermediateHashes] wrong trie root: 4a92f2a08dfe4ce5d495c6d795b5cf68b0a2dde182493d739fe30de8b7fdcd29, expected (from header): 3f3157550eb9698cca3e9f481daede81006a65f1fa388f302dfccf7439bc4fe8
```

**Comment by sjlee1125** [comment] 2023-05-17 06:04
In my case, v1.0.6
even after ```state_stages``` don't work.
```
[INFO] [05-17|05:53:44.083] [2/15 Headers] Processed                 highest inserted=29869923 age=1s
[INFO] [05-17|05:53:44.083] [2/15 Headers] DONE                      in=5m17.15609357s
[INFO] [05-17|05:53:51.154] [5/15 Bodies] Processing bodies...       from=29861199 to=29869923
[INFO] [05-17|05:54:03.729] [5/15 Bodies] Processed                  highest=29869923
[INFO] [05-17|05:54:03.729] [6/15 Senders] Started                   from=29861199 to=29869923
[INFO] [05-17|05:54:05.321] [7/15 Execution] Blocks execution        from=29861199 to=29869923
[WARN] [05-17|05:54:05.321] [7/15 Execution] Execution failed        block=29861200 hash=0xf21360c3b70fbaf1ebaa67fb58b3a7a5f3301d54c076554fb0f1619285943a6d err="mismatching validator list on epoch block"
[INFO] [05-17|05:54:05.321] UnwindTo                                 block=29861199 bad_block_hash=0xf21360c3b70fbaf1ebaa67fb58b3a7a5f3301d54c076554fb0f1619285943a6d
[INFO] [05-17|05:54:05.322] [7/15 Execution] Completed on            block=29861199
[INFO] [05-17|05:54:05.519] Timings (slower than 50ms)               Headers=5m17.156s BlockHashes=7.059s Bodies=12.574s Senders=1.592s Unwind Bodies=102ms Unwind Headers=91ms
[INFO] [05-17|05:54:05.527] RPC Daemon notified of new headers       from=29861003 to=29869923 hash=0x0000000000000000000000000000000000000000000000000000000000000000 header sending=7.932032ms log sending=279ns
[INFO] [05-17|05:54:05.527] [2/15 Headers] Waiting for headers...    from=29861199
[INFO] [05-17|05:54:25.527] [2/15 Headers] No block headers to write in this log period block number=29861199
```

**Comment by mateipopp** [comment] 2023-05-17 10:33
I unwinded and my nodes are still stuck. I'm using v1.0.6. 
Logs:
```
ay 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.406] Set global gas cap                       cap=50000000
May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.420] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=1000mb upload.rate=4mb
May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.420] Opening Database                         label=chaindata path=/node/data/chaindata
May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.420] [db] params: growStep=2GB, mapsSize=1800GB, shrinkThreshold=-1, pageSize=4KB, label=chaindata, WriteMap=false, Durable=false, NoRead>May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: mdbx_ipclock_failed:31512 wlock owner died, recovering
May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.422] Initialised chain configuration          config="{ChainID: 97 Ramanujan: 1010000, Niels: 1014369, MirrorSync: 5582500, Bruno: 138370>May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.422] Effective                                prune_flags= snapshot_flags= history.v3=false
May 17 10:11:20 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:20.429] Initialising Ethereum protocol           network=97
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.147] Starting private RPC server              on=0.0.0.0:9090
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.147] rpc filters: subscribing to Erigon events
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.147] new subscription to logs established
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.147] New txs subscriber joined
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.147] new subscription to newHeaders established
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.148] Reading JWT secret                       path=/node/data/jwt.hex
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.148] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.151] Started P2P networking                   version=66 self=enode://2e7dda4cebd620113fb4fddf8a6c6a25c942f38fcb5da9eab669994c5808b9381cd>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.158] [2/15 Headers] Waiting for headers...    from=29873966
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [INFO] [05-17|10:11:21.429] [txpool] Started
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.458] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873967 blockHash=0x100f356916adeb6688598f6459865c806>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.462] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873968 blockHash=0x896323bb9de0f2f8024caacf2ddd307f0>
May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.462] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873968 blockHash=0x896323bb9de0f2f8024caacf2ddd307f0>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.462] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873968 blockHash=0x896323bb9de0f2f8024caacf2ddd307f0>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.465] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873969 blockHash=0x4947b24de2c4acdc37690ae718bdd7627>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.465] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873969 blockHash=0x4947b24de2c4acdc37690ae718bdd7627>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.469] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873970 blockHash=0x4ce850799123505335fb245f9262eb8e5>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.469] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873970 blockHash=0x4ce850799123505335fb245f9262eb8e5>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.473] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873971 blockHash=0x469cc7d4de6166c879213fbf3283e46ff>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.473] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873971 blockHash=0x469cc7d4de6166c879213fbf3283e46ff>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.473] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873972 blockHash=0x4cd49a25e296833b0b65e451586d0d7cb>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.473] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873972 blockHash=0x4cd49a25e296833b0b65e451586d0d7cb>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.477] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873973 blockHash=0x432ddbdd627072d1cb198278d0b41258a>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.477] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873973 blockHash=0x432ddbdd627072d1cb198278d0b41258a>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.480] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873974 blockHash=0x0c16aca7f69306378b63130b0df1a97f4>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.480] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873974 blockHash=0x0c16aca7f69306378b63130b0df1a97f4>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.484] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873975 blockHash=0xbc02ab1861b20c12ccc95c5648d72c52a>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.484] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873975 blockHash=0xbc02ab1861b20c12ccc95c5648d72c52a>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.488] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873976 blockHash=0x724e57022e4ea077ab19dfe965c935fe7>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.488] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873976 blockHash=0x724e57022e4ea077ab19dfe965c935fe7>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.491] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873977 blockHash=0xb6f53fee5cb660d224bc4f7fbc23d1e54>May 17 10:11:21 bsc-archive-testnet-0-eu erigon[887019]: [EROR] [05-17|10:11:21.491] Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=29873977 blockHash=0xb6f53fee5cb660d224bc4f7fbc23d1e54>
```

**Comment by setunapo** [comment] 2023-05-17 10:53
update: not fixed yet.
We are still working on it, we will update once it is fixed.

**Comment by setunapo** [comment] 2023-05-17 12:11
I think we have found the root cause: should be fixed by https://github.com/node-real/bsc-erigon/pull/82
Since the database was broken on our device, it would take us some time to verify, could be 1 or 2 hours

**Comment by pc-quiknode** [comment] 2023-05-17 14:17
@setunapo the release breaks after I've rolledback to a block prior to the fork following the instruction
```
erigon[12608]: [WARN] [05-17|14:00:38.401] [7/15 Execution] Execution failed        block=29861005 hash=0xc40826844ba0f4ecba6e710decd3bf25433cddca5771508ea1604f8d38cfb303 err="mismatched receipt headers for block 29861005 (0x7b541c337f373371940ef7161edf282289710547bed0705bab2a1b7871e304e4 != 0xf883a59fa01ff3bc0485f7cc43092f3fbc34a5f4fcccf3bdb74e3c1255428d67)"
```

**Comment by setunapo** [comment] 2023-05-17 22:01
> the release breaks after I've rolledback to a block prior to the fork following the instruction

@pc-quiknode how did you do rollback, could you provide your detail cmd of unwind?
the changes of v1.0.7 only take effect after plato upgrade, 29861005 is not there yet.
May not same sure, not sure if your DB is still consistent

**Comment by pc-quiknode** [comment] 2023-05-17 23:08
@setunapo Confirmed that the latest release works with a clean database. Thank you for the fix.

**Comment by brilliant-lx** [comment] 2023-05-18 01:09
> 

That's great, thank you for you feedback!
And our node is still syncing, I think we need to provide a snapshot for testnet later.

**Comment by setunapo** [comment] 2023-05-18 01:10
Great, kind of you to give the feedback. Our node is still syncing, I think we need to provide a snapshot for testnet later.

**Comment by tsutsu** [comment] 2023-05-21 08:41
Also confirmed, works with a clean sync from scratch.

Seemingly, something that happened in one of the intervening versions of erigon-bsc, corrupted the DB, such that even rewinding by all stages by millions of blocks wasn't enough to fix it. It would be nice to know what exactly that corruption was, but it's not important as long as it doesn't happen again.

**Closed** 2023-05-22 08:45 UTC
