### ISSUE TITLE
[2/15 Headers] No block headers to write in this log period block

### ISSUE THREAD

**Issue by harveyff** [node-real/bsc-erigon#104] opened 2023-05-26 12:51 UTC
Hi teams,

Thank you for your great work,

After upgrading to version 1.0.8, the situation of "[2/15 Headers] No block headers to write in this log period block" has been greatly improved, but it still occurs occasionally, sometimes every two or three days.

I have 2 machines running separately, their hardware configuration is the same, machine 2 has not been upgraded, it is still 1.0.7, what is strange is that it has been running stably for more than a week, and there is no block lag (and are all continuous blocks).

Is it possible to continue to improve this situation? Thank you so much for your continued dedication.

**Comment by Normalizex** [comment] 2023-05-26 16:40
Hello, I am facing a similar issue.
I also made the upgrade to v1.0.8.

The second time I ran with the flag "--sentry.drop-useless-peers" and still it didn't change the situation much.

**Comment by nikolinsko** [comment] 2023-05-28 10:12
@Normalizex did you check how sentry.drop-useless-peers affected your connection count?

Mine dropped from to configured max conns of 300 to about 30-35 and never increased beyond that.

**Comment by fylsan3** [comment] 2023-06-02 07:22
如果需要经常重启的话请删掉--p2p.protocol=参数再试试，我删除后情况好了很多

**Comment by koraykoska** [comment] 2023-06-04 20:06
This is becoming a real problem. Why do you keep closing the issues mentioning this? It's getting worse, not better. And restarting is obviously not the solution. Does anyone have an idea what the cause is?

**Comment by setunapo** [comment] 2023-06-15 02:36
Seems the situation is much better now?
Do you still have this issue? it is much stable in our own environment with the latest release.

**Comment by koraykoska** [comment] 2023-06-15 13:57
@setunapo No it's exactly the same as always. I don't understand what "much stable" means. Is it stable or not? It's not stable if it reaches this state every few days.

Right now there are 2 distinct bugs. 1 that prints the following:

`No block headers to write in this log period block `

And one with this:

`No block bodies to write in this log period block `

**Comment by Doc-Pixel** [comment] 2023-06-16 18:21
Same issue happening here. Restart "fixes" it, feels like erigon hits a dead end from a code perspective when this specific situation occurs and can't continue normal operation.

**Comment by hitchhooker** [comment] 2023-06-20 00:20
situation was fixed for a while and seems to have re-emerged last week again.

**Comment by StoneMoe** [comment] 2023-06-21 04:07
experiencing this issue after a downloader warning, which shows "rejected header marked as bad"
```
{"in":"66.699659ms","lvl":"info","msg":"Commit cycle","t":"2023-06-20T20:13:58.053390774+08:00"}                                                                                                                                            
{"Bodies":"213ms","Execution":"96ms","Headers":"2.454s","IntermediateHashes":"67ms","lvl":"info","msg":"Timings (slower than 50ms)","t":"2023-06-20T20:13:58.053446374+08:00"}                                                              
{"AccountChangeSet":"567.0GB","BlockTransaction":"115.9GB","FreeList":"26.2MB","PlainState":"246.3GB","ReclaimableSpace":"105.0GB","StorageChangeSet":"1.3TB","TransactionLog":"2.3TB","lvl":"info","msg":"Tables","t":"2023-06-20T20:13:58.
053475125+08:00"}                                                                                                                                                                                                                           
{"from":29266109,"hash":"0x211c23de178357e2f61368a9c566b23a667e58400f4af1327a378dec309c2f61","header sending":"14.392µs","log sending":"516ns","lvl":"info","msg":"RPC Daemon notified of new headers","t":"2023-06-20T20:13:58.053528152+08
:00","to":29266110}                                                                                                                                                                                                                         
{"from":29266110,"lvl":"info","msg":"[2/15 Headers] Waiting for headers...","t":"2023-06-20T20:13:58.103946534+08:00"}                                                                                                                      
{"age":"1s","highest inserted":29266111,"lvl":"info","msg":"[2/15 Headers] Processed","t":"2023-06-20T20:14:01.563826019+08:00"}                                                                                                            
{"block":29266111,"lvl":"info","msg":"[7/15 Execution] Completed on","t":"2023-06-20T20:14:02.039467122+08:00"}                                                                                                                             
{"in":"55.14785ms","lvl":"info","msg":"Commit cycle","t":"2023-06-20T20:14:02.246592735+08:00"}                                                                                                                                             
{"Bodies":"400ms","Headers":"3.459s","IntermediateHashes":"50ms","lvl":"info","msg":"Timings (slower than 50ms)","t":"2023-06-20T20:14:02.246652317+08:00"}                                                                                 
{"AccountChangeSet":"567.0GB","BlockTransaction":"115.9GB","FreeList":"26.2MB","PlainState":"246.3GB","ReclaimableSpace":"105.0GB","StorageChangeSet":"1.3TB","TransactionLog":"2.3TB","lvl":"info","msg":"Tables","t":"2023-06-20T20:14:02.
24667582+08:00"}                                                                                                                                                                                                                            
{"from":29266110,"hash":"0xb2f052b8be3551364d9edc717c0bce03399c0a90857631bec7024dd8017b6acd","header sending":"16.389µs","log sending":"543ns","lvl":"info","msg":"RPC Daemon notified of new headers","t":"2023-06-20T20:14:02.246745472+08
:00","to":29266111}                                                                                                                                                                                                                         
{"from":29266111,"lvl":"info","msg":"[2/15 Headers] Waiting for headers...","t":"2023-06-20T20:14:02.309934155+08:00"}                                                                                                                      
{"age":"0","highest inserted":29266112,"lvl":"info","msg":"[2/15 Headers] Processed","t":"2023-06-20T20:14:04.550259896+08:00"}                                                                                                             
{"block":29266112,"lvl":"info","msg":"[7/15 Execution] Completed on","t":"2023-06-20T20:14:04.976333871+08:00"}                                                                                                                             {"in":"113.67002ms","lvl":"info","msg":"Commit cycle","t":"2023-06-20T20:14:05.408737398+08:00"}                                                                                                                                            
{"Bodies":"212ms","Execution":"188ms","Headers":"2.24s","IntermediateHashes":"113ms","lvl":"info","msg":"Timings (slower than 50ms)","t":"2023-06-20T20:14:05.408792216+08:00"}
{"AccountChangeSet":"567.0GB","BlockTransaction":"115.9GB","FreeList":"26.2MB","PlainState":"246.3GB","ReclaimableSpace":"105.0GB","StorageChangeSet":"1.3TB","TransactionLog":"2.3TB","lvl":"info","msg":"Tables","t":"2023-06-20T20:14:05.
408806794+08:00"}                                                                                                                                                                                                                           
{"from":29266111,"hash":"0x07fcc031552ceddd9edfbf4bc957d1e1c03d4de6db25a86c66f4f7e955f7841b","header sending":"15.141µs","log sending":"496ns","lvl":"info","msg":"RPC Daemon notified of new headers","t":"2023-06-20T20:14:05.408856726+08
:00","to":29266112}                                                                                                                                                                                                                         
{"from":29266112,"lvl":"info","msg":"[2/15 Headers] Waiting for headers...","t":"2023-06-20T20:14:05.487925896+08:00"}         
{"bad_block_hash":"0x0000000000000000000000000000000000000000000000000000000000000000","block":29266110,"lvl":"info","msg":"UnwindTo","t":"2023-06-20T20:14:06.755953254+08:00"}
{"age":"1s","highest inserted":29266112,"lvl":"info","msg":"[2/15 Headers] Processed","t":"2023-06-20T20:14:06.756025301+08:00"}                                                                                                            {"codes":true,"from":29266112,"lvl":"info","msg":"[8/15 HashState] Unwinding started","storage":false,"t":"2023-06-20T20:14:06.92024829+08:00","to":29266110}
{"codes":false,"from":29266112,"lvl":"info","msg":"[8/15 HashState] Unwinding started","storage":false,"t":"2023-06-20T20:14:06.941764734+08:00","to":29266110}                                                                             {"codes":false,"from":29266112,"lvl":"info","msg":"[8/15 HashState] Unwinding started","storage":true,"t":"2023-06-20T20:14:06.947159792+08:00","to":29266110}
{"csbucket":"AccountChangeSet","from":29266112,"lvl":"info","msg":"[9/15 IntermediateHashes] Unwinding","t":"2023-06-20T20:14:06.96178966+08:00","to":29266110}
{"csbucket":"StorageChangeSet","from":29266112,"lvl":"info","msg":"[9/15 IntermediateHashes] Unwinding","t":"2023-06-20T20:14:06.965072585+08:00","to":29266110}                                         
{"hash":"0x32fda669c5eff2a2291a3a93cb5fcf59d62e0a0e1ff6d68eadf59a09eeb5de28","lvl":"info","msg":"[9/15 IntermediateHashes] Trie root","t":"2023-06-20T20:14:07.05540641+08:00"}
{"from":29266112,"lvl":"info","msg":"[7/15 Execution] Unwind Execution","t":"2023-06-20T20:14:07.086826976+08:00","to":29266110}                    
{"block":29266112,"lvl":"info","msg":"[7/15 Execution] Completed on","t":"2023-06-20T20:14:08.03716071+08:00"}                                                                                                                              
{"lvl":"eror","msg":"[9/15 IntermediateHashes] Wrong trie root of block 29266112: 4aefede2a4eb6f4bb5688d4f2259d77420604f3f98e4360a0bd4fa7930fdc904, expected (from header): c8f2603cf3bccb8310d7a08fc632c35442e9362583a037f00d1ffb6fb8ff7348
. Block hash: 5f791ecfd75e8920126320a5a5fc1952cac938ea8d65136c443de8df3db3cae0","t":"2023-06-20T20:14:08.68716442+08:00"}                           
{"lvl":"warn","msg":"Unwinding due to incorrect root hash","t":"2023-06-20T20:14:08.687237212+08:00","to":29266111}                                                                                                                         
{"bad_block_hash":"0x5f791ecfd75e8920126320a5a5fc1952cac938ea8d65136c443de8df3db3cae0","block":29266111,"lvl":"info","msg":"UnwindTo","t":"2023-06-20T20:14:08.687274227+08:00"}
{"codes":true,"from":29266112,"lvl":"info","msg":"[8/15 HashState] Unwinding started","storage":false,"t":"2023-06-20T20:14:08.687330311+08:00","to":29266111}
{"codes":false,"from":29266112,"lvl":"info","msg":"[8/15 HashState] Unwinding started","storage":false,"t":"2023-06-20T20:14:08.690768066+08:00","to":29266111}                                                         
{"codes":false,"from":29266112,"lvl":"info","msg":"[8/15 HashState] Unwinding started","storage":true,"t":"2023-06-20T20:14:08.695129812+08:00","to":29266111}
{"from":29266112,"lvl":"info","msg":"[7/15 Execution] Unwind Execution","t":"2023-06-20T20:14:08.70436766+08:00","to":29266111}                                                                                          
{"in":"223.533529ms","lvl":"info","msg":"Commit cycle","t":"2023-06-20T20:14:08.948487823+08:00"}                                                                                                                                           
{"Bodies":"215ms","Execution":"652ms","HashState":"359ms","Headers":"1.268s","IntermediateHashes":"290ms","Senders":"55ms","Unwind IntermediateHashes":"125ms","lvl":"info","msg":"Timings (slower than 50ms)","t":"2023-06-20T20:14:08.9485
37421+08:00"}                                                                                                                                                                                                                               
{"AccountChangeSet":"567.0GB","BlockTransaction":"115.9GB","FreeList":"26.3MB","PlainState":"246.3GB","ReclaimableSpace":"105.1GB","StorageChangeSet":"1.3TB","TransactionLog":"2.3TB","lvl":"info","msg":"Tables","t":"2023-06-20T20:14:08.
948556792+08:00"}                                                                                                                                                                                                                           
{"from":29266111,"lvl":"info","msg":"[2/15 Headers] Waiting for headers...","t":"2023-06-20T20:14:09.096867509+08:00"}                                                                                                   
{"hash":"0x5f791ecfd75e8920126320a5a5fc1952cac938ea8d65136c443de8df3db3cae0","height":29266112,"lvl":"warn","msg":"[downloader] Rejected header marked as bad","t":"2023-06-20T20:14:11.854426832+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:14:29.096904382+08:00"}                                                                     
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:14:49.097105477+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:15:09.097044627+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:15:29.097177059+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:15:49.097650563+08:00"}
{"dups":2040,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":78,"respMax":29266146,"respMin":29266110,"skel":15,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:15:49.0977814+08:00"}
{"eth66":"6","lvl":"info","msg":"[p2p] GoodPeers","t":"2023-06-20T20:15:51.975337786+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:16:09.09788535+08:00"}
{"dups":2137,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":71,"respMax":29266153,"respMin":29266110,"skel":13,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:16:09.09797651+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:16:29.09746839+08:00"}
{"dups":2485,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":65,"respMax":29266159,"respMin":29266110,"skel":14,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:16:29.097571832+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:16:49.097522581+08:00"}
{"dups":2961,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":74,"respMax":29266166,"respMin":29266110,"skel":13,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:16:49.097596002+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:17:09.097491112+08:00"}
{"dups":3616,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":74,"respMax":29266172,"respMin":27367683,"skel":15,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:17:09.097615338+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:17:29.097955564+08:00"}
{"dups":3739,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":77,"respMax":29266179,"respMin":29266110,"skel":14,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:17:29.098205693+08:00"}
{"block number":29266111,"lvl":"info","msg":"[2/15 Headers] No block headers to write in this log period","t":"2023-06-20T20:17:49.097255685+08:00"}
{"dups":3818,"lvl":"info","msg":"Req/resp stats","req":0,"reqMax":0,"reqMin":0,"resp":68,"respMax":29266186,"respMin":29266110,"skel":13,"skelMax":29266302,"skelMin":29266110,"t":"2023-06-20T20:17:49.097377505+08:00"}
{"eth66":"7","lvl":"info","msg":"[p2p] GoodPeers","t":"2023-06-20T20:17:51.974941703+08:00"}
```

**Comment by calmbeing** [comment] 2023-06-26 09:15
There're many reasons for "No block header to write" not only purely because of sync node, for recent reasons, some cases are block execution failed, this was fixed already in the latest commit. And for the p2p protocol stuff, we will continuously optimize it for better experience. Please leave any advise if any

**Comment by calmbeing** [comment] 2023-06-29 01:34
As the perspective we saw recent days, the p2p sentry node is basically stable. This problem mostly due to other cases. And recent cases were almost "execution failed" and "intermediate hash unwind", the "execution failed" was addressed already, and we're looking into "intermediate hash unwind". Will merged into https://github.com/node-real/bsc-erigon/issues/121. Please reopen if any other problems.

**Closed by calmbeing** 2023-06-29 01:34 UTC
